### ISSUE TITLE
 Consensys zkEVM - Linea is now able to be added

### ISSUE THREAD

**Issue by karasakalmt** [sayajin-labs/zk-evm-exploration#10]
Since more data is released about Linea -> https://docs.linea.build/architecture it now can be documented

**Comment by MartianGreed** [comment]
Hey ! 
If you have some time anytime soon, feel free to fill a PR ! :)

**Comment by karasakalmt** [comment]
https://github.com/kkrt-labs/zk-evm-exploration/pull/11
